# Generated by Django 5.0.1 on 2024-01-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='vendors',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='vendors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.vendor'),
        ),
    ]
