# Generated by Django 5.0.1 on 2024-01-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin1.vendor'),
        ),
    ]
