# Generated by Django 4.2.5 on 2024-01-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_food_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_price', to='admin1.food'),
        ),
    ]
