# Generated by Django 4.2.5 on 2024-01-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_offer_status_alter_offer_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
