# Generated by Django 4.2.5 on 2024-01-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_remove_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=200),
        ),
    ]
