# Generated by Django 4.2.5 on 2024-01-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
