# Generated by Django 5.0 on 2024-01-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0013_remove_order_food_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
