# Generated by Django 4.2.5 on 2024-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0015_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=200),
        ),
    ]
