# Generated by Django 4.2.5 on 2024-02-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0018_rename_amount_order_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_date',
        ),
    ]
